#!/usr/bin/env python3
"""
Script to verify Nagini modules generated by the nagini_converter.py.
This script runs Nagini verification on all modules in the nagini_modules directory.
"""
import os
import sys
import subprocess
import argparse
import json
import datetime
import re
from typing import List, Optional, Dict, Any, Tuple


def check_float_encoding(module_path: str) -> bool:
    """Check if the module has float_encoding=False.
    
    Args:
        module_path: Path to the module file
        
    Returns:
        True if float encoding should be used, False otherwise
    """
    try:
        with open(module_path, 'r') as f:
            content = f.read()
            # Look for float_encoding = False
            if re.search(r'float_encoding\s*=\s*False', content):
                return False
        return True
    except Exception:
        # Default to True if we can't read the file
        return True


def verify_module(module_path: str, verbose: bool = False) -> Dict[str, Any]:
    """Verify a single module with Nagini.
    
    Args:
        module_path: Path to the module file to verify
        verbose: Whether to print full error output to console
        
    Returns:
        Dictionary with verification results including full logs
    """
    module_name = os.path.basename(module_path)
    print(f"Verifying {module_name}...")
    
    result_data = {
        "module": module_name,
        "path": module_path,
        "verification_result": "unknown",
        "error_message": "",
        "full_log": "",
        "timestamp": datetime.datetime.now().isoformat()
    }
    
    # Check if this module needs float encoding
    use_float_encoding = check_float_encoding(module_path)
    
    try:
        # Construct command based on float encoding setting
        cmd = ["nagini", "--verbose", module_path]
        if use_float_encoding:
            cmd.insert(1, "real")
            cmd.insert(1, "--float-encoding")
            float_msg = "with float encoding"
        else:
            float_msg = "without float encoding"
        
        print(f"  Running Nagini {float_msg}")
        
        # Run the command
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
        )
        
        # Store full log - always capture everything regardless of verbose flag
        result_data["full_log"] = result.stdout + result.stderr
        
        if result.returncode == 0:
            print(f"✅ {module_name}: Verified")
            result_data["verification_result"] = "success"
            return result_data
        else:
            print(f"❌ {module_name}: Failed")
            result_data["verification_result"] = "failure"
            
            # Extract error message
            error_lines = result.stderr.strip().split('\n')
            main_error = next((line for line in error_lines if "Error:" in line), "Unknown error")
            result_data["error_message"] = main_error
            
            # Print error details to console based on verbose flag
            if verbose:
                print("\nError details:")
                print("-" * 80)
                print(result.stderr)
                print("-" * 80)
            else:
                print(f"  {main_error}")
                print("  (Run with --verbose for full error details in console)")
            
            return result_data
    except FileNotFoundError:
        error_msg = "Error: Nagini executable not found. Make sure Nagini is installed and in your PATH."
        print(error_msg)
        result_data["verification_result"] = "error"
        result_data["error_message"] = error_msg
        return result_data
    except Exception as e:
        error_msg = f"Error verifying {module_path}: {e}"
        print(error_msg)
        result_data["verification_result"] = "error"
        result_data["error_message"] = str(e)
        return result_data


def get_module_paths(modules_dir: str, specific_modules: Optional[List[str]] = None) -> List[str]:
    """Get paths to modules that should be verified.
    
    Args:
        modules_dir: Directory containing Nagini modules
        specific_modules: Optional list of specific module names to verify
        
    Returns:
        List of paths to modules to verify
    """
    if not os.path.exists(modules_dir):
        print(f"Error: Directory {modules_dir} does not exist.")
        return []

    # Get all Python files in the directory
    all_python_files = [
        os.path.join(modules_dir, f)
        for f in os.listdir(modules_dir)
        if f.endswith(".py")
    ]

    if not all_python_files:
        print(f"No Python files found in {modules_dir}.")
        return []
    
    # If specific modules are specified, filter to those modules
    if specific_modules:
        # Add .py extension if not present
        specific_modules_with_ext = [
            m if m.endswith(".py") else f"{m}.py" for m in specific_modules
        ]
        
        filtered_files = [
            f for f in all_python_files 
            if os.path.basename(f) in specific_modules_with_ext
        ]
        
        if not filtered_files:
            print(f"None of the specified modules found in {modules_dir}.")
            print(f"Available modules: {', '.join(os.path.basename(f) for f in all_python_files)}")
            return []
        
        return sorted(filtered_files)
    
    return sorted(all_python_files)


def main():
    """Verify Nagini modules in the nagini_modules directory."""
    # Parse command-line arguments
    parser = argparse.ArgumentParser(description="Verify Nagini modules")
    parser.add_argument(
        "--modules-dir", 
        default=None,
        help="Directory containing Nagini modules (defaults to nagini_modules in script directory)"
    )
    parser.add_argument(
        "--results-file",
        default=None,
        help="Path to save results JSON (defaults to nagini_results.json in script directory)"
    )
    parser.add_argument(
        "--verbose", "-v", 
        action="store_true", 
        help="Print full error output to console (full logs are always saved to the results file)"
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=60,
        help="Timeout in seconds for each verification (default: 60)"
    )
    parser.add_argument(
        "modules", 
        nargs="*", 
        help="Specific modules to verify (defaults to all modules)"
    )
    
    args = parser.parse_args()
    
    # Get the directory of the script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Use specified modules directory or default to nagini_modules in script directory
    modules_dir = args.modules_dir or os.path.join(script_dir, "nagini_modules")
    
    # Use specified results file or default to nagini_results.json in script directory
    results_file = args.results_file or os.path.join(script_dir, "nagini_results.json")
    
    print(f"Verifying Nagini modules in: {modules_dir}")
    print(f"Results will be saved to: {results_file}")
    print(f"Verbose console output: {'enabled' if args.verbose else 'disabled'}")
    print(f"Full logs will always be captured in the results file\n")
    
    # Get modules to verify
    python_files = get_module_paths(modules_dir, args.modules)
    
    if not python_files:
        return 1

    # Verify each file and collect results
    results = []
    success_count = 0
    failure_count = 0
    error_count = 0
    
    for module_path in python_files:
        try:
            # Set timeout for subprocess to prevent hanging
            subprocess.run(["timeout", str(args.timeout)], capture_output=True, text=True)
            result_data = verify_module(module_path, args.verbose)
        except KeyboardInterrupt:
            print("\nVerification process interrupted by user.")
            # Add info about the interrupted module
            result_data = {
                "module": os.path.basename(module_path),
                "path": module_path,
                "verification_result": "interrupted",
                "error_message": "Verification process interrupted by user",
                "full_log": "",
                "timestamp": datetime.datetime.now().isoformat()
            }
            results.append(result_data)
            break
        
        results.append(result_data)
        
        if result_data["verification_result"] == "success":
            success_count += 1
        elif result_data["verification_result"] == "failure":
            failure_count += 1
        else:
            error_count += 1

    # Calculate total of verified modules (might be less than total if interrupted)
    verified_total = success_count + failure_count + error_count
    total = len(python_files)
    interrupted = total - verified_total > 0
    
    # Create summary data
    summary = {
        "total_modules": total,
        "verified_modules": verified_total,
        "success_count": success_count,
        "failure_count": failure_count,
        "error_count": error_count,
        "interrupted": interrupted,
        "unverified_count": total - verified_total,
        "success_rate": (success_count / verified_total * 100) if verified_total > 0 else 0,
        "timestamp": datetime.datetime.now().isoformat()
    }
    
    # Combine results and summary in a single JSON
    output_data = {
        "summary": summary,
        "results": results
    }
    
    # Save results to JSON file
    with open(results_file, 'w') as f:
        json.dump(output_data, f, indent=2)
    
    # Print summary statistics
    print("\nVerification Summary:")
    print(f"Total modules: {total}")
    if interrupted:
        print(f"Verified modules: {verified_total} (verification was interrupted)")
        print(f"Unverified modules: {total - verified_total}")
    
    print(f"Successfully verified: {success_count}")
    print(f"Failed verification: {failure_count}")
    print(f"Verification errors: {error_count}")
    
    if verified_total > 0:
        success_rate = (success_count / verified_total) * 100
        print(f"Success rate: {success_rate:.1f}%")
    
    print(f"\nResults saved to: {results_file}")

    return 0 if success_count == total else 1


if __name__ == "__main__":
    sys.exit(main())
